name: Pipeline Docker Image
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 19
          uses: actions/setup-java@v3
          with:
            java-version: '19'
            distribution: 'temurin'
 
        - name: Git Version
          id: version
          uses: codacy/git-version@2.7.1
 
        - name: Docker Build & Push Action
          uses: mr-smithers-excellent/docker-build-push@v6.4
          with:
           image: irenatobarros/devops_test2
           tag: ${{ steps.version.outputs.version }}, ${{ github.run_number }}
           registry: docker.io
           USERNAME: ${{ secrets.DOCKER_USERNAME }}
           PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
